automation:
  - alias: Update packages from GitHub
    triggers:
      - trigger: template
        value_template: >
          {{ now().weekday() == 6 and now().hour == 3 and now().minute == 0 }}
      - trigger: state
        entity_id: input_boolean.manual_update_packages
        to: 'on'
    actions:
      - action: shell_command.update_packages_from_github
      - delay: "00:00:05"
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.manual_update_packages
