automation:
  - alias: "Battery – Update Smart Charging When New Prices Arrive"
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.sem_nordpool_tomorrow_prices_available
        from: "off"
        to: "on"
    action:
      - service: input_button.press
        target:
          entity_id: input_button.sem_update_battery_cheapest_charge
